NITE 1.5.1 - API Reference: XnV3DVector Class Reference
XnV3DVector Class Reference
#include <XnV3DVector.h>
Public Member Functions
XnV3DVector ()
XnV3DVector (XnFloat fX, XnFloat fY, XnFloat fZ)
XnV3DVector (const XnPoint3D &ptOther)
XnV3DVector (const XnV3DVector &v3Other)
XnV3DVector (XnFloat f)
XnV3DVector (XnFloat *pf)
XnV3DVector & operator= (const XnV3DVector &v3Rhs)
XnV3DVector & operator= (const XnPoint3D &ptRhs)
XnFloat operator[] (XnUInt32 index) const
XnFloat & operator[] (XnUInt32 index)
XnV3DVector & Set (const XnV3DVector &v3Other)
XnV3DVector & Set (const XnPoint3D &ptOther)
XnV3DVector & Set (XnFloat fX, XnFloat fY, XnFloat fZ)
XnV3DVector & Set (XnFloat f)
XnV3DVector & SetZero ()
XnBool IsZero () const
XnBool operator== (const XnV3DVector &v3Rhs) const
XnBool operator!= (const XnV3DVector &v3Rhs) const
XnV3DVector operator- () const
XnV3DVector & Negate (const XnV3DVector &v3Other)
XnV3DVector & Negate ()
XnV3DVector operator* (const XnV3DVector &v3Rhs) const
XnV3DVector & operator*= (const XnV3DVector &v3Rhs)
XnV3DVector & Multiply (const XnV3DVector &v3Lhs, const XnV3DVector &v3Rhs)
XnV3DVector & Multiply (XnFloat f, const XnV3DVector &v3Rhs)
XnV3DVector operator* (XnFloat f) const
XnV3DVector & operator*= (XnFloat f)
XnV3DVector & Multiply (const XnV3DVector &v3Lhs, XnFloat f)
XnV3DVector operator/ (XnFloat f) const
XnV3DVector & operator/= (XnFloat f)
XnV3DVector & Divide (const XnV3DVector &v3Lhs, XnFloat f)
XnV3DVector operator+ (const XnV3DVector &v3Rhs) const
XnV3DVector & operator+= (const XnV3DVector &v3Rhs)
XnV3DVector & Add (const XnV3DVector &v3Lhs, const XnV3DVector &v3Rhs)
XnV3DVector operator+ (XnFloat f) const
XnV3DVector & operator+= (XnFloat f)
XnV3DVector & Add (const XnV3DVector &v3Lhs, XnFloat f)
XnV3DVector operator- (const XnV3DVector &v3Rhs) const
XnV3DVector & operator-= (const XnV3DVector &v3Rhs)
XnV3DVector & Subtract (const XnV3DVector &v3Lhs, const XnV3DVector &v3Rhs)
XnV3DVector operator- (XnFloat f) const
XnV3DVector & operator-= (XnFloat f)
XnV3DVector & Subtract (const XnV3DVector &v3Lhs, XnFloat f)
XnV3DVector & Sqrt ()
XnV3DVector & Sqrt (const XnV3DVector &v3Other)
XnFloat Magnitude () const
XnFloat MagnitudeSquared () const
XnFloat Distance (const XnV3DVector &v3Other) const
XnFloat DistanceSquared (const XnV3DVector &v3Other) const
XnFloat Normalize ()
XnV3DVector & OrthogonalVector (const XnV3DVector &v3Other)
XnV3DVector & UnitOrthogonalVector (const XnV3DVector &v3Other)
XnV3DVector operator^ (const XnV3DVector &v3Rhs) const
XnV3DVector & CrossProduct (const XnV3DVector &v3Lhs, const XnV3DVector &v3Rhs)
XnFloat operator| (const XnV3DVector &v3Rhs) const
XnV3DVector & Interpolate (const XnV3DVector &v3Vec1, const XnV3DVector &v3Vec2, XnFloat fAlpha)
XnBool IsSameDirection (const XnV3DVector &v3Other) const
XnFloat GetTolerance () const
void SetTolerance (XnFloat fTolerance)
Protected Attributes
XnFloat m_fTolerance
Friends
XnV3DVector operator* (XnFloat f, const XnV3DVector &v3Rhs)
XnFloat DotProduct (const XnV3DVector &v3Lhs, const XnV3DVector &v3Rhs)
Detailed Description
Definition at line 23 of file XnV3DVector.h.
Constructor & Destructor Documentation
XnV3DVector::XnV3DVector () [inline]
Definition at line 144 of file XnV3DVector.h.
References Set().
Referenced by operator*(), operator+(), operator-(), and operator/().
XnV3DVector::XnV3DVector (XnFloat fX, XnFloat fY, XnFloat fZ) [inline]
Definition at line 149 of file XnV3DVector.h.
References Set().
XnV3DVector::XnV3DVector (const XnPoint3D & ptOther) [inline]
Definition at line 158 of file XnV3DVector.h.
References Set().
XnV3DVector::XnV3DVector (const XnV3DVector & v3Other) [inline]
Definition at line 154 of file XnV3DVector.h.
References Set().
XnV3DVector::XnV3DVector (XnFloat f) [inline]
Definition at line 162 of file XnV3DVector.h.
References Set().
XnV3DVector::XnV3DVector (XnFloat * pf) [inline]
Definition at line 167 of file XnV3DVector.h.
References Set().
Member Function Documentation
XnV3DVector & XnV3DVector::Add (const XnV3DVector & v3Lhs, const XnV3DVector & v3Rhs) [inline]
Definition at line 335 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::Add (const XnV3DVector & v3Lhs, XnFloat f) [inline]
Definition at line 348 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::CrossProduct (const XnV3DVector & v3Lhs, const XnV3DVector & v3Rhs) [inline]
Definition at line 459 of file XnV3DVector.h.
References Set().
Referenced by operator^().
XnFloat XnV3DVector::Distance (const XnV3DVector & v3Other) const [inline]
Definition at line 404 of file XnV3DVector.h.
References DistanceSquared().
XnFloat XnV3DVector::DistanceSquared (const XnV3DVector & v3Other) const [inline]
Definition at line 408 of file XnV3DVector.h.
Referenced by Distance().
XnV3DVector & XnV3DVector::Divide (const XnV3DVector & v3Lhs, XnFloat f) [inline]
Definition at line 321 of file XnV3DVector.h.
References Set().
XnFloat XnV3DVector::GetTolerance () const [inline]
Definition at line 134 of file XnV3DVector.h.
References m_fTolerance.
XnV3DVector & XnV3DVector::Interpolate (const XnV3DVector & v3Vec1, const XnV3DVector & v3Vec2, XnFloat fAlpha) [inline]
Definition at line 479 of file XnV3DVector.h.
References Set().
XnBool XnV3DVector::IsSameDirection (const XnV3DVector & v3Other) const [inline]
Definition at line 485 of file XnV3DVector.h.
References IsZero(), XnVMathCommon::IsZero(), and m_fTolerance.
XnBool XnV3DVector::IsZero () const [inline]
Definition at line 243 of file XnV3DVector.h.
References m_fTolerance.
Referenced by IsSameDirection().
XnFloat XnV3DVector::Magnitude () const [inline]
Definition at line 392 of file XnV3DVector.h.
References MagnitudeSquared().
Referenced by Normalize().
XnFloat XnV3DVector::MagnitudeSquared () const [inline]
Definition at line 396 of file XnV3DVector.h.
Referenced by Magnitude().
XnV3DVector & XnV3DVector::Multiply (const XnV3DVector & v3Lhs, const XnV3DVector & v3Rhs) [inline]
Definition at line 285 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::Multiply (XnFloat f, const XnV3DVector & v3Rhs) [inline]
Definition at line 294 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::Multiply (const XnV3DVector & v3Lhs, XnFloat f) [inline]
Definition at line 307 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::Negate (const XnV3DVector & v3Other) [inline]
Definition at line 267 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::Negate () [inline]
Definition at line 271 of file XnV3DVector.h.
References Set().
XnFloat XnV3DVector::Normalize () [inline]
Definition at line 414 of file XnV3DVector.h.
References m_fTolerance, Magnitude(), and Set().
Referenced by UnitOrthogonalVector().
XnBool XnV3DVector::operator!= (const XnV3DVector & v3Rhs) const [inline]
Definition at line 257 of file XnV3DVector.h.
References operator==().
XnV3DVector XnV3DVector::operator* (const XnV3DVector & v3Rhs) const [inline]
Definition at line 277 of file XnV3DVector.h.
References XnV3DVector().
XnV3DVector XnV3DVector::operator* (XnFloat f) const [inline]
Definition at line 299 of file XnV3DVector.h.
References XnV3DVector().
XnV3DVector & XnV3DVector::operator*= (const XnV3DVector & v3Rhs) [inline]
Definition at line 281 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::operator*= (XnFloat f) [inline]
Definition at line 303 of file XnV3DVector.h.
References Set().
XnV3DVector XnV3DVector::operator+ (const XnV3DVector & v3Rhs) const [inline]
Definition at line 327 of file XnV3DVector.h.
References XnV3DVector().
XnV3DVector XnV3DVector::operator+ (XnFloat f) const [inline]
Definition at line 340 of file XnV3DVector.h.
References XnV3DVector().
XnV3DVector & XnV3DVector::operator+= (const XnV3DVector & v3Rhs) [inline]
Definition at line 331 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::operator+= (XnFloat f) [inline]
Definition at line 344 of file XnV3DVector.h.
References Set().
XnV3DVector XnV3DVector::operator- () const [inline]
Definition at line 263 of file XnV3DVector.h.
References XnV3DVector().
XnV3DVector XnV3DVector::operator- (const XnV3DVector & v3Rhs) const [inline]
Definition at line 354 of file XnV3DVector.h.
References XnV3DVector().
XnV3DVector XnV3DVector::operator- (XnFloat f) const [inline]
Definition at line 367 of file XnV3DVector.h.
References XnV3DVector().
XnV3DVector & XnV3DVector::operator-= (const XnV3DVector & v3Rhs) [inline]
Definition at line 358 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::operator-= (XnFloat f) [inline]
Definition at line 371 of file XnV3DVector.h.
References Set().
XnV3DVector XnV3DVector::operator/ (XnFloat f) const [inline]
Definition at line 313 of file XnV3DVector.h.
References XnV3DVector().
XnV3DVector & XnV3DVector::operator/= (XnFloat f) [inline]
Definition at line 317 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::operator= (const XnV3DVector & v3Rhs) [inline]
Definition at line 174 of file XnV3DVector.h.
References m_fTolerance, and Set().
XnV3DVector & XnV3DVector::operator= (const XnPoint3D & ptRhs) [inline]
Definition at line 179 of file XnV3DVector.h.
References m_fTolerance, and Set().
XnBool XnV3DVector::operator== (const XnV3DVector & v3Rhs) const [inline]
Definition at line 251 of file XnV3DVector.h.
References m_fTolerance.
Referenced by operator!=().
XnFloat XnV3DVector::operator[] (XnUInt32 index) const [inline]
Definition at line 186 of file XnV3DVector.h.
XnFloat & XnV3DVector::operator[] (XnUInt32 index) [inline]
Definition at line 200 of file XnV3DVector.h.
XnV3DVector XnV3DVector::operator^ (const XnV3DVector & v3Rhs) const [inline]
Definition at line 452 of file XnV3DVector.h.
References CrossProduct().
XnFloat XnV3DVector::operator| (const XnV3DVector & v3Rhs) const [inline]
Definition at line 467 of file XnV3DVector.h.
References DotProduct.
XnV3DVector & XnV3DVector::OrthogonalVector (const XnV3DVector & v3Other) [inline]
Definition at line 426 of file XnV3DVector.h.
References Set().
Referenced by UnitOrthogonalVector().
XnV3DVector & XnV3DVector::Set (const XnV3DVector & v3Other) [inline]
Definition at line 216 of file XnV3DVector.h.
Referenced by Add(), CrossProduct(), Divide(), Interpolate(), Multiply(), Negate(), Normalize(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), OrthogonalVector(), Set(), SetZero(), Sqrt(), Subtract(), and XnV3DVector().
XnV3DVector & XnV3DVector::Set (const XnPoint3D & ptOther) [inline]
Definition at line 220 of file XnV3DVector.h.
XnV3DVector & XnV3DVector::Set (XnFloat fX, XnFloat fY, XnFloat fZ) [inline]
Definition at line 225 of file XnV3DVector.h.
XnV3DVector & XnV3DVector::Set (XnFloat f) [inline]
Definition at line 233 of file XnV3DVector.h.
References Set().
void XnV3DVector::SetTolerance (XnFloat fTolerance) [inline]
Definition at line 139 of file XnV3DVector.h.
References m_fTolerance.
XnV3DVector & XnV3DVector::SetZero () [inline]
Definition at line 239 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::Sqrt () [inline]
Definition at line 380 of file XnV3DVector.h.
References Set().
Referenced by Sqrt().
XnV3DVector & XnV3DVector::Sqrt (const XnV3DVector & v3Other) [inline]
Definition at line 385 of file XnV3DVector.h.
References Set(), and Sqrt().
XnV3DVector & XnV3DVector::Subtract (const XnV3DVector & v3Lhs, const XnV3DVector & v3Rhs) [inline]
Definition at line 362 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::Subtract (const XnV3DVector & v3Lhs, XnFloat f) [inline]
Definition at line 375 of file XnV3DVector.h.
References Set().
XnV3DVector & XnV3DVector::UnitOrthogonalVector (const XnV3DVector & v3Other) [inline]
Definition at line 443 of file XnV3DVector.h.
References Normalize(), and OrthogonalVector().
Friends And Related Function Documentation
XnFloat DotProduct (const XnV3DVector & v3Lhs, const XnV3DVector & v3Rhs) [friend]
Definition at line 471 of file XnV3DVector.h.
Referenced by operator|().
XnV3DVector operator* (XnFloat f, const XnV3DVector & v3Rhs) [friend]
Definition at line 290 of file XnV3DVector.h.
Member Data Documentation
XnFloat XnV3DVector::m_fTolerance [protected]
Definition at line 131 of file XnV3DVector.h.
Referenced by GetTolerance(), IsSameDirection(), IsZero(), Normalize(), operator=(), operator==(), and SetTolerance().
The documentation for this class was generated from the following file:
XnV3DVector.h