NITE 1.5.1 - API Reference: XnVMathCommon Namespace Reference
XnVMathCommon Namespace Reference
Functions
void Exchange (XnFloat &a, XnFloat &b)
void ExchangeSort (XnFloat &a, XnFloat &b)
void ExchangeSort (XnFloat &a, XnFloat &b, XnFloat &c)
XnFloat Sqr (XnFloat a)
XnFloat Max (XnFloat a, XnFloat b)
XnFloat Min (XnFloat a, XnFloat b)
XnFloat MaxAbs (XnFloat a, XnFloat b)
XnFloat MinAbs (XnFloat a, XnFloat b)
XnUInt16 ArgMax (XnFloat a, XnFloat b)
XnUInt16 ArgMax (XnFloat a, XnFloat b, XnFloat c)
XnUInt16 ArgMin (XnFloat a, XnFloat b)
XnUInt16 ArgMin (XnFloat a, XnFloat b, XnFloat c)
XnBool IsZero (XnFloat f, XnFloat fTolerance)
Variables
const XnFloat PI = 3.14159265f
const XnFloat HALF_PI = (PI/2)
Function Documentation
XnUInt16 XnVMathCommon::ArgMax (XnFloat a, XnFloat b) [inline]
Definition at line 66 of file XnVMathCommon.h.
Referenced by ArgMin().
XnUInt16 XnVMathCommon::ArgMax (XnFloat a, XnFloat b, XnFloat c) [inline]
Definition at line 71 of file XnVMathCommon.h.
XnUInt16 XnVMathCommon::ArgMin (XnFloat a, XnFloat b) [inline]
Definition at line 76 of file XnVMathCommon.h.
References ArgMax().
XnUInt16 XnVMathCommon::ArgMin (XnFloat a, XnFloat b, XnFloat c) [inline]
Definition at line 81 of file XnVMathCommon.h.
References ArgMax().
void XnVMathCommon::Exchange (XnFloat & a, XnFloat & b) [inline]
Definition at line 18 of file XnVMathCommon.h.
Referenced by ExchangeSort().
void XnVMathCommon::ExchangeSort (XnFloat & a, XnFloat & b) [inline]
Definition at line 25 of file XnVMathCommon.h.
References Exchange().
void XnVMathCommon::ExchangeSort (XnFloat & a, XnFloat & b, XnFloat & c) [inline]
Definition at line 31 of file XnVMathCommon.h.
References Exchange().
XnBool XnVMathCommon::IsZero (XnFloat f, XnFloat fTolerance) [inline]
Definition at line 89 of file XnVMathCommon.h.
Referenced by XnV3DVector::IsSameDirection().
XnFloat XnVMathCommon::Max (XnFloat a, XnFloat b) [inline]
Definition at line 46 of file XnVMathCommon.h.
Referenced by MaxAbs().
XnFloat XnVMathCommon::MaxAbs (XnFloat a, XnFloat b) [inline]
Definition at line 56 of file XnVMathCommon.h.
References Max().
XnFloat XnVMathCommon::Min (XnFloat a, XnFloat b) [inline]
Definition at line 51 of file XnVMathCommon.h.
Referenced by MinAbs().
XnFloat XnVMathCommon::MinAbs (XnFloat a, XnFloat b) [inline]
Definition at line 61 of file XnVMathCommon.h.
References Min().
XnFloat XnVMathCommon::Sqr (XnFloat a) [inline]
Definition at line 41 of file XnVMathCommon.h.
Variable Documentation
const XnFloat XnVMathCommon::HALF_PI = (PI/2)
Definition at line 87 of file XnVMathCommon.h.
const XnFloat XnVMathCommon::PI = 3.14159265f
Definition at line 86 of file XnVMathCommon.h.